import { Inter } from 'next/font/google';
import SelectGroup from '@/components/SelectGroup';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Players',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<section className={inter.className}>
			<SelectGroup />
			{children}
		</section>
	);
}
