import { Inter } from 'next/font/google';
import PlayerSearchSelectGroup from '@/components/group/PlayerSelect/PlayerSearchSelectGroup';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Players',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<section className={`${inter.className} h-[calc(100dvh-56px)] fixed inset-x-0 overflow-auto`}>
			<PlayerSearchSelectGroup />
			{children}
		</section>
	);
}
