import Header from '@/components/Header';
import './globals.css';
import { Inter } from 'next/font/google';
import RQProvider from '@/components/RQProvider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { Analytics } from '@vercel/analytics/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Draftd',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<RQProvider>
					<div>
						<Header />
						{children}
					</div>
					{/* <ReactQueryDevtools /> */}
				</RQProvider>
				< Analytics />
			</body>
		</html>
	);
}
