import Header from '@/components/Header';
import { ReactQueryProvider } from './ReactQueryProvider';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Draftd',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<ReactQueryProvider>
				<body className={inter.className}>
					<Header />
					{children}
				</body>
			</ReactQueryProvider>
		</html>
	);
}
